### ISSUE TITLE
Get DOM nodes back instead of HTML

### ISSUE THREAD

**Issue by fregante** [sindresorhus/linkify-urls#2]
Passing raw text and getting HTML can cause XSS: https://github.com/sindresorhus/refined-github/issues/510

`linkify-urls` could return a `DocumentFragment` like:

```
"textNode", Node(a[href=link](link)), "textNode"
```

**Comment by sindresorhus** [comment]
👍 Good idea. I think it should be a separate method though, as the current way can be useful in non-browser environments.
