### ISSUE TITLE
Support of non-ASCII urls

### ISSUE THREAD

**Issue by tuoxiansp** [sindresorhus/linkify-urls#23]
Please support CJK urls like:  https://语c.com

see https://runkit.com/tuoxiansp/5c68df202420a30012202c06

I also tested url-regex, this supports well:

https://runkit.com/tuoxiansp/5c68de8514a5c10014ac66c2

**Comment by sindresorhus** [comment]
Sure. PR welcome. I think you can use the regex `u` flag and `\p{L}` (letters) and `\p{Nd}` (digits). We cannot use the `url-regex` package as it has some other limitations.
