### ISSUE TITLE
urlRegex does't work in Safari, please fix

### ISSUE THREAD

**Issue by ulmanss** [sindresorhus/linkify-urls#24]
urlRegex does't work in Safari. SyntaxError: Invalid regular expression: invalid group specifier name.

Problem in (?<!\+)

Thnx.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in older browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by vesamet** [comment]
For those who stumble on this issue, the library [LinkifyJs](https://github.com/Hypercontext/linkifyjs) is a good alternative for all modern browsers.
For Node.js project I would still go with [sindresorhus](https://github.com/sindresorhus) solution.
