### ISSUE TITLE
Use `url-regex` module again

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/linkify-urls#9]
Depends on it handling parens: https://github.com/kevva/url-regex/pull/35#issuecomment-331970744

**Comment by sindresorhus** [comment]
// @kevva

**Comment by fregante** [comment]
The package is abandoned, this fork seems to be supported: https://github.com/spamscanner/url-regex-safe

**Comment by fregante** [comment]
I looked into this, `url-regex-safe` breaks all the improvements we made to the regex, like:

- https://github.com/sindresorhus/linkify-urls/pull/13
- https://github.com/sindresorhus/linkify-urls/pull/21

Since one is dead and the other one _also_ has several issues, I'm going to close this.
